#pragma once

#define COLORTWISTLIB_HASIPP  1

#define COLORTWISTLIB_HASAVX  1

#define COLORTWISTLIB_HASNEON  0

#define COLORTWISTLIB_CANUSENEONINTRINSIC_VCVTNQ_U32_F32 0

#define COLORTWISTLIB_HAS_SYS_AUXV_H 0
